let activeCategory="fem",sb;
function initSupabase(){if(!window.SUPABASE_URL||window.SUPABASE_URL.includes("COLE_AQUI")){document.getElementById("syncStatus").textContent="Configuração do banco pendente";return false;}sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);return true;}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
async function loadAll(){if(!sb)return;const [{data:teams},{data:matches},{data:sponsors,error:sponsorsError}]=await Promise.all([sb.from("teams").select("*").order("name"),sb.from("matches").select("*").order("match_time"),sb.from("sponsors").select("*").order("position").order("name")]);render(teams||[],matches||[]);renderSponsors(sponsorsError?[]:(sponsors||[]));document.getElementById("syncStatus").textContent="Atualizado agora";}
function matchPointTotals(m){return {a:(m.set1_a||0)+(m.set2_a||0)+(m.set3_a||0),b:(m.set1_b||0)+(m.set2_b||0)+(m.set3_b||0)}}
function tieBreakOrder(a,b,ties){const m=ties.find(x=>(x.team_a===a.id&&x.team_b===b.id)||(x.team_a===b.id&&x.team_b===a.id));if(!m)return 0;const winner=m.sets_a>m.sets_b?m.team_a:m.team_b;return winner===a.id?-1:1;}
function hasTieWinner(a,b,ties){return ties.some(m=>((m.team_a===a&&m.team_b===b)||(m.team_a===b&&m.team_b===a))&&m.sets_a!==m.sets_b)}
function buildStandings(teams,matches,cat,group){let rows=teams.filter(t=>t.category===cat&&t.group_code===group).map(t=>({id:t.id,name:t.name,j:0,v:0,p:0,pf:0,pa:0,desempate:false}));matches.filter(m=>m.category===cat&&(m.phase||"Grupo")==="Grupo"&&m.status==="Finalizado").forEach(m=>{const a=rows.find(r=>r.id===m.team_a),b=rows.find(r=>r.id===m.team_b);if(!a||!b)return;const pt=matchPointTotals(m);a.j++;b.j++;a.pf+=pt.a;a.pa+=pt.b;b.pf+=pt.b;b.pa+=pt.a;if(m.sets_a===2){a.v++;if(m.sets_b===0)a.p+=3;else{a.p+=2;b.p+=1}}else if(m.sets_b===2){b.v++;if(m.sets_a===0)b.p+=3;else{b.p+=2;a.p+=1}}});const ties=matches.filter(m=>m.category===cat&&m.phase==="Desempate"&&m.status==="Finalizado");rows.sort((a,b)=>b.p-a.p||((b.pf-b.pa)-(a.pf-a.pa))||tieBreakOrder(a,b,ties)||a.name.localeCompare(b.name));for(let i=0;i<rows.length-1;i++){const a=rows[i],b=rows[i+1];if(a.p===b.p&&(a.pf-a.pa)===(b.pf-b.pa)&&!hasTieWinner(a.id,b.id,ties))a.desempate=b.desempate=true;}return rows;}
function setLine(m){const sets=[[m.set1_a,m.set1_b],[m.set2_a,m.set2_b],[m.set3_a,m.set3_b]].filter(([a,b])=>(a||0)>0||(b||0)>0);return sets.length?sets.map(([a,b])=>`${a||0}-${b||0}`).join(" • "):"";}
function render(teams,matches){document.getElementById("tabs").innerHTML=`<button class="tab ${activeCategory==="fem"?"active":""}" onclick="setCat('fem')">Feminino • 4ª Edição</button><button class="tab ${activeCategory==="masc"?"active":""}" onclick="setCat('masc')">Masculino • 1ª Edição</button>`;const teamMap=Object.fromEntries(teams.map(t=>[t.id,t.name]));const ms=matches.filter(m=>m.category===activeCategory);document.getElementById("matches").innerHTML=ms.length?ms.map(m=>{const status=m.status==="Ao vivo"?"<span class='live'>● AO VIVO</span>":m.status==="Finalizado"?"<span class='done'>✓ FINALIZADO</span>":esc(m.status);const shown=m.status==="Agendado"?"×":`${m.sets_a} × ${m.sets_b}`;const detail=setLine(m);return `<div class="match"><div class="team">${esc(teamMap[m.team_a]||"A definir")}<div class="meta">${esc(m.match_time?.slice(0,5)||"--:--")} • ${esc(m.court||"Quadra")} • ${esc(m.phase||"Grupo")}</div></div><div class="score">${shown}<div class="meta">${status}</div>${detail?`<div class="set-detail">${detail}</div>`:""}</div><div class="team right">${esc(teamMap[m.team_b]||"A definir")}</div></div>`}).join(""):"<p class='muted'>Nenhum jogo cadastrado.</p>";document.getElementById("standings").innerHTML=["A","B"].map(g=>{const rows=buildStandings(teams,matches,activeCategory,g);return `<div class="public-group"><h3>Chave ${g}</h3><div class="table-wrap"><table><thead><tr><th>#</th><th>Equipe</th><th>J</th><th>V</th><th>PF</th><th>PS</th><th>Saldo</th><th>Pts</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="${r.desempate?"needs-tiebreak":""}"><td>${i+1}</td><td><b>${esc(r.name)}</b>${r.desempate?" <span title='Jogo de desempate necessário'>⚠️</span>":""}</td><td>${r.j}</td><td>${r.v}</td><td>${r.pf}</td><td>${r.pa}</td><td>${r.pf-r.pa}</td><td><b>${r.p}</b></td></tr>`).join("")}</tbody></table></div></div>`}).join("");}
function renderSponsors(sponsors){const box=document.getElementById("sponsors");box.innerHTML=sponsors.length?sponsors.map(s=>`<div class="sponsor-card" title="${esc(s.name)}"><img src="${esc(s.logo_url)}" alt="${esc(s.name)}" loading="lazy"><span>${esc(s.name)}</span></div>`).join(""):"<span class='muted'>Em breve</span>";}
function setCat(c){activeCategory=c;loadAll()}window.setCat=setCat;
document.addEventListener("DOMContentLoaded",async()=>{if(!initSupabase())return;await loadAll();sb.channel("taca-sg-live").on("postgres_changes",{event:"*",schema:"public",table:"matches"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"teams"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"sponsors"},loadAll).subscribe();});
